# Generated by Django 5.1.2 on 2024-10-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footbalarea',
            name='iamge',
            field=models.ImageField(blank=True, null=True, upload_to='football_areas/'),
        ),
    ]
