# Generated by Django 5.1.2 on 2024-10-22 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_footbalarea_iamge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footbalarea',
            old_name='iamge',
            new_name='image',
        ),
    ]
