# Generated by Django 5.1.2 on 2024-10-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_rename_iamge_footbalarea_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='footbalarea',
            name='grass_type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
